import type { FinanceState } from './models'

const now = new Date().toISOString()

export const initialFinanceState: FinanceState = {
  categories: [
    {
      id: 'cat-salary',
      name: 'Salary',
      color: '#49d17d',
      kind: 'income',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-freelance',
      name: 'Freelance',
      color: '#59c6ff',
      kind: 'income',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-food',
      name: 'Food',
      color: '#ff8b5f',
      kind: 'expense',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-transport',
      name: 'Transport',
      color: '#4f8bff',
      kind: 'expense',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-housing',
      name: 'Housing',
      color: '#a97cff',
      kind: 'expense',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-shopping',
      name: 'Shopping',
      color: '#ffd24d',
      kind: 'expense',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
    {
      id: 'cat-fun',
      name: 'Fun',
      color: '#ff5f8f',
      kind: 'expense',
      isDefault: true,
      createdAt: now,
      updatedAt: now,
      syncStatus: 'synced',
    },
  ],
  transactions: [],
  budgets: [],
  syncQueue: [],
  settings: {
    theme: 'dark',
    currency: 'USD',
    syncEndpoint: 'demo://local',
    conflictPolicy: 'client-wins',
    hasSeenPrivacyModal: false,
    backupRemindersEnabled: true,
    lastBackupAt: null,
    changesSinceBackup: 0,
    lastReminderAt: null,
  },
  lastSyncedAt: null,
  lastSyncAttemptAt: null,
  lastSyncError: null,
}
