import type { FinanceState } from './models'
import {
  UNCATEGORIZED_CATEGORY_COLOR,
  UNCATEGORIZED_CATEGORY_ID,
  UNCATEGORIZED_CATEGORY_NAME,
} from './categories'

const now = new Date().toISOString()

export const initialFinanceState: FinanceState = {
  categories: [
    {
      id: UNCATEGORIZED_CATEGORY_ID,
      name: UNCATEGORIZED_CATEGORY_NAME,
      color: UNCATEGORIZED_CATEGORY_COLOR,
      kind: 'both',
      system: 'uncategorized',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-salary',
      name: 'Salary',
      color: '#49d17d',
      kind: 'income',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-freelance',
      name: 'Freelance',
      color: '#59c6ff',
      kind: 'income',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-food',
      name: 'Food',
      color: '#ff8b5f',
      kind: 'expense',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-transport',
      name: 'Transport',
      color: '#4f8bff',
      kind: 'expense',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-housing',
      name: 'Housing',
      color: '#a97cff',
      kind: 'expense',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-shopping',
      name: 'Shopping',
      color: '#ffd24d',
      kind: 'expense',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-fun',
      name: 'Fun',
      color: '#ff5f8f',
      kind: 'expense',
      system: null,
      createdAt: now,
      updatedAt: now,
    },
  ],
  transactions: [],
  budgets: [],
  recurringTemplates: [],
  settings: {
    theme: 'dark',
    currency: 'USD',
    hasSeenPrivacyModal: false,
    backupRemindersEnabled: true,
    lastBackupAt: null,
    changesSinceBackup: 0,
    lastReminderAt: null,
  },
}
